apiVersion: apps/v1
kind: Deployment
metadata:
  name: rose-client-deployment
  labels:
    app: rose-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rose-client
  template:
    metadata:
      labels:
        app: rose-client
    spec:
      containers:
      - name: rose-client-container
        image: quay.io/rose/rose-client:latest  # Modify with your Docker image name and tag.
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: rose-client-service
spec:
  selector:
    app: rose-client
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
